global using JulietsStore;
global using JulietsStore.App.Abstracts;
global using JulietsStore.App.Models;
global using JulietsStore.Domain.Abstracts;
global using JulietsStore.Domain.Models;
global using JulietsStore.Domain.ViewModels;
global using JulietsStore.Extensions;
global using JulietsStore.Infra.Data;
global using JulietsStore.ViewModels;